import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ChevronDown, Clock3, ExternalLink, RefreshCw, Trophy } from 'lucide-react';
import { apiFetch } from '../services/apiConfig';

type Match={id:string;leagueId:number;league:string;home:string;away:string;homeScore:number|null;awayScore:number|null;status:'LIVE'|'UPCOMING'|'FT'|'POSTPONED'|'CANCELLED';statusText:string;kickoffUtc:string;kickoffEAT:string;kickoffSwahili?:string;source:'FotMob';sourceUrl:string};
type Dashboard={generatedAt:string;timezone:string;season:string;sources:string[];leagues:{id:number;name:string}[];live:Match[];today:Match[];upcoming:Match[];previous:Match[]};
const empty:Dashboard={generatedAt:'',timezone:'Africa/Dar_es_Salaam',season:'',sources:['FotMob','LiveScore','Azam Sports','Azam Media'],leagues:[],live:[],today:[],upcoming:[],previous:[]};

const Sport:React.FC<{onBack:()=>void;onToggleMenu:()=>void}>=({onBack,onToggleMenu})=>{
 const [data,setData]=useState<Dashboard>(empty); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [section,setSection]=useState<'live'|'today'|'upcoming'|'previous'>('today'); const [league,setLeague]=useState('all');
 const load=async()=>{setLoading(true);setError('');try{const d=await apiFetch<Dashboard>('/api/sport');setData(d||empty);}catch(e:any){setError(e?.message||'Sport data haipatikani kwa sasa.');}finally{setLoading(false);}};
 useEffect(()=>{load();const id=window.setInterval(load,30000);return()=>window.clearInterval(id);},[]);
 const items=useMemo(()=>{const a=section==='live'?data.live:section==='today'?data.today:section==='upcoming'?data.upcoming:data.previous;return league==='all'?a:a.filter(m=>String(m.leagueId)===league);},[data,section,league]);
 const tabs:[['live','LIVE SASA'],['today','LEO'],['upcoming','ZIJAZO'],['previous','ZILIZOPITA']]=[['live','LIVE SASA'],['today','LEO'],['upcoming','ZIJAZO'],['previous','ZILIZOPITA']];
 return <div className='flex-1 h-full overflow-y-auto bg-[#131314]'>
  <div className='sticky top-0 z-20 bg-[#131314]/95 backdrop-blur border-b border-[#24252b] px-4 sm:px-6 py-3'>
   <div className='flex items-center justify-between gap-3'><div className='flex items-center gap-3'><button onClick={onToggleMenu} className='lg:hidden p-2 rounded-xl bg-[#1b1c21]'><Activity className='w-5 h-5'/></button><button onClick={onBack} className='p-2 rounded-xl bg-[#1b1c21] text-[#D4AF37]'>←</button><div><h1 className='text-lg sm:text-xl font-bold'>Sport</h1><p className='text-[11px] text-[#858894]'>LiveScore • Ratiba • Matokeo • Saa za Tanzania (EAT) • {data.season||'msimu wa sasa'}</p></div></div><button onClick={load} disabled={loading} className='p-2.5 rounded-xl border border-[#33343b] hover:border-[#D4AF37]'><RefreshCw className={'w-4 h-4 '+(loading?'animate-spin':'')}/></button></div>
   <div className='flex gap-2 mt-3 overflow-x-auto pb-1'>{tabs.map(([key,label])=><button key={key} onClick={()=>setSection(key as any)} className={'px-3 py-2 rounded-xl text-xs font-bold whitespace-nowrap '+(section===key?'bg-[#D4AF37] text-black':'bg-[#1b1c21] text-[#a4a6ae]')}>{label}{key==='live'&&data.live.length?' • '+data.live.length:''}</button>)}</div>
   <div className='relative mt-2'><select value={league} onChange={e=>setLeague(e.target.value)} className='w-full appearance-none bg-[#1b1c21] border border-[#303139] rounded-xl px-3 py-2.5 text-xs text-[#f0f4f9] outline-none'><option value='all'>Ligi zote</option>{data.leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><ChevronDown className='absolute right-3 top-3 w-4 h-4 pointer-events-none text-[#888]'/></div>
   <div className='flex flex-wrap gap-1.5 mt-3'>{data.sources.map(s=><span key={s} className='px-2 py-1 rounded-lg bg-[#D4AF37]/10 border border-[#D4AF37]/20 text-[10px] text-[#D4AF37]'>{s}</span>)}<span className='px-2 py-1 rounded-lg bg-[#1f2026] border border-[#33343b] text-[10px] text-[#a4a6ae]'>Muda: EAT (Tanzania UTC+3)</span></div>
  </div>
  <div className='p-4 sm:p-6 space-y-3'>{error&&<div className='p-4 rounded-2xl border border-red-500/30 bg-red-500/10 text-sm text-red-300'>{error}</div>}{loading&&!items.length&&<div className='p-8 text-center text-sm text-[#888]'>Inapakia live scores na fixtures...</div>}{!loading&&!items.length&&!error&&<div className='p-8 text-center rounded-2xl border border-[#282930] bg-[#17181d] text-sm text-[#888]'>{section==='live'?'Hakuna mechi inayoendelea LIVE kwa sasa. Fungua “LEO” kuona mechi za leo.':'Hakuna mechi zilizopatikana kwa chaguo hili.'}</div>}
   {items.map(m=><div key={m.id} className='rounded-2xl border border-[#292a31] bg-[#17181d] p-4 hover:border-[#D4AF37]/40 transition'><div className='flex items-center justify-between gap-2 mb-3'><div className='flex items-center gap-2 text-[10px] text-[#8d8f99]'><Trophy className='w-3.5 h-3.5 text-[#D4AF37]'/>{m.league}</div><span className={'text-[10px] font-bold px-2 py-1 rounded-lg '+(m.status==='LIVE'?'bg-red-500/15 text-red-300':m.status==='FT'?'bg-emerald-500/10 text-emerald-300':'bg-[#22232a] text-[#b7b9c1]')}>{m.status==='LIVE'?'LIVE':m.status==='FT'?'FT':m.statusText}</span></div>
    <div className='grid grid-cols-[1fr_auto_1fr] items-center gap-3'><div className='text-sm font-semibold text-right'>{m.home}</div><div className='text-center min-w-[72px]'><div className='text-xl font-black'>{m.homeScore===null?'—':m.homeScore} <span className='text-[#777]'>-</span> {m.awayScore===null?'—':m.awayScore}</div><div className='text-[10px] text-[#888] mt-1 flex flex-col items-center justify-center gap-0.5'><div className='flex items-center justify-center gap-1 font-semibold text-[#c0c2cc] whitespace-nowrap'><Clock3 className='w-3 h-3 text-[#D4AF37]'/>{m.kickoffEAT}</div>{m.kickoffSwahili&&<span className='text-[9px] text-[#D4AF37] font-medium whitespace-nowrap'>{m.kickoffSwahili}</span>}</div></div><div className='text-sm font-semibold'>{m.away}</div></div>
    <div className='mt-3 pt-3 border-t border-[#24252b] flex justify-between items-center text-[10px] text-[#777]'><span>Chanzo cha data: FotMob</span><a href={m.sourceUrl} target='_blank' rel='noreferrer' className='flex items-center gap-1 text-[#D4AF37]'>Fungua <ExternalLink className='w-3 h-3'/></a></div></div>)}
  </div>
 </div>;
};
export default Sport;